// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-QQrMkX6Oo0_u50w7RwFfMwriiEpRxKw',
    appId: '1:117071959344:web:470d59f03fd1792456a4f5',
    messagingSenderId: '117071959344',
    projectId: 'safetyapp-flutte',
    authDomain: 'safetyapp-flutte.firebaseapp.com',
    storageBucket: 'safetyapp-flutte.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX1AmsLzuAN7jn-skB-Qx8QpTFms7Lx50',
    appId: '1:117071959344:android:1cdf95003aa26fd056a4f5',
    messagingSenderId: '117071959344',
    projectId: 'safetyapp-flutte',
    storageBucket: 'safetyapp-flutte.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtN4hhiVO0nZDdMCSz56Bh5bzMk0UJOfY',
    appId: '1:117071959344:ios:4436f2a442ce9fac56a4f5',
    messagingSenderId: '117071959344',
    projectId: 'safetyapp-flutte',
    storageBucket: 'safetyapp-flutte.firebasestorage.app',
    iosBundleId: 'com.example.smartSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtN4hhiVO0nZDdMCSz56Bh5bzMk0UJOfY',
    appId: '1:117071959344:ios:4436f2a442ce9fac56a4f5',
    messagingSenderId: '117071959344',
    projectId: 'safetyapp-flutte',
    storageBucket: 'safetyapp-flutte.firebasestorage.app',
    iosBundleId: 'com.example.smartSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-QQrMkX6Oo0_u50w7RwFfMwriiEpRxKw',
    appId: '1:117071959344:web:45e68934182d760e56a4f5',
    messagingSenderId: '117071959344',
    projectId: 'safetyapp-flutte',
    authDomain: 'safetyapp-flutte.firebaseapp.com',
    storageBucket: 'safetyapp-flutte.firebasestorage.app',
  );
}
